import pandas as pd
from pandas import DataFrame
import numpy as np
import matplotlib.pyplot as plt 
import pymongo
from pymongo import MongoClient, errors
import glob 
import json

# query into duckdb database 
client = MongoClient("mongodb+srv://<username>:<password>@ds4320proj2.p0udp7x.mongodb.net/")

# print(client.list_database_names())

# accessing my database
database = client["DSProj2"]

# turning those collections into dictionaries again 
unplanned_all = pd.DataFrame(list(database.unplanned_data.find({})))
readm_all = pd.DataFrame(list(database.readm_data.find({})))
plants_all = pd.DataFrame(list(database.plants_data.find({})))
generators_all = pd.DataFrame(list(database.generators_data.find({})))
demand_all = pd.DataFrame(list(database.demand_data.find({})))

# investigating schema 
# unplanned_all.info()
# demand_all.info()
# plants_all.info()
# generators_all.info()
# demand_all.info()

# removing the _id columns generated by mongo for our own analysis  
unplanned_all = unplanned_all.drop(["_id"], axis=1) 
readm_all = readm_all.drop(["_id"], axis=1)
plants_all = plants_all.drop(["_id"], axis=1)
generators_all = generators_all.drop(["_id"], axis=1)
demand_all = demand_all.drop(["_id"], axis=1) 

# average excess readm rate per hospital 
readm_per_hospital = readm_all.merge(
    unplanned_all,
    on="Facility Name",
    how="left"
)
readm_per_hospital.head()

# average excess readm per zip code 
ex_readm_avg = (
    zip_per_hospital
    .groupby("ZIP", as_index=False)["Excess Readmission Ratio"]
    .mean()
    .rename(columns={"Excess Readmission Ratio": "Excess_Readm_Avg"})
)

# one hot encoder for plant data 
encoded_technology = pd.get_dummies(generators_all["Technology"], dtype=int)
# surprise tool to help us later
encoded_tech_columns = list(encoded_technology.columns)

# Displaying the encoded DataFrame
# encoded_technology.head()

# dropping technology column from generators data so we don't have repetiton 
generators_all = generators_all.drop(["Technology"], axis=1)
# generators_all.head()

# average monthly demand per plant 
demand_no_only = demand_all.groupby("Plant Name").mean()

# average monthly demand per plant DATAFRAME 
plants_and_demand = plants_all.merge(
    demand_no_only,
    on="Plant Name",
    how="left"
)
plants_and_demand.head()

# dropping state data because i realised i dont need it
plants_and_demand = plants_and_demand.drop(["State"], axis=1) 
plants_and_demand.head()

# making a comprehensive dataframe with the generator table and the 1hotencoder technology 
generators_and_tech = pd.concat([generators_all, encoded_technology], axis=1)
generators_and_tech.head()

# average 'type of generator' per plant 
plant_generators = (
    generators_and_tech.groupby('Plant Name')
      .agg({
          **{col: 'mean' for col in encoded_tech_columns},
          'County': 'first',
          'State': 'first',
      })
      .reset_index()
)
plant_generators.head()

# that previous dataframe, but with monthly de
plants_everything = plants_and_demand.merge(
    plant_generators,
    on="Plant Name",
    how="left"
)
plants_everything.head()
